import http from"node:http";import fs from"node:fs/promises";import fsSync from"node:fs";import path from"node:path";import crypto from"node:crypto";import archiver from"archiver";import{providerCatalog}from"./lib/catalog.mjs";import{encryptSecret,decryptSecret}from"./lib/crypto.mjs";import{ProviderRouter}from"./lib/router.mjs";import{safePath,assertWorkspaceWritePath,runCommand,walkTree}from"./lib/sandbox.mjs";import{isDueToday}from"./lib/scheduler.mjs";import{connectorCatalog}from"./lib/connectors.mjs";import{buildFallbackPlan,parseModelPlan}from"./lib/agent.mjs";import{fitPayload}from"./lib/context.mjs";import{inspectLocalModel,localProvider}from"./lib/models.mjs";import{compileWorkflow,validateWorkflow}from"./lib/workflow.mjs";import{collectUrl,curate,saveStaged}from"./lib/learning.mjs";import{normalizeStoryboard,validateClipRequest}from"./lib/media.mjs";
const PORT=Number(process.env.PORT||4174),ROOT=path.resolve(process.env.LEVELING_WORKSPACE||"./workspace"),DATA=path.join(ROOT,".leveling"),PROVIDERS=path.join(DATA,"providers.json"),TASKS=path.join(DATA,"tasks.json"),LEARNING=path.join(DATA,"learning.json"),MASTER=String(process.env.LEVELING_MASTER_KEY||""),DEV="replace-with-a-long-random-secret",MAX=5000000;
async function ensure(){await fs.mkdir(ROOT,{recursive:true});await fs.mkdir(DATA,{recursive:true});for(const[f,i]of[[PROVIDERS,"[]"],[TASKS,"[]"],[LEARNING,JSON.stringify({stagedRecords:0,curatedRecords:0,candidateCheckpoint:null,candidateScore:null,promoted:false})]])try{await fs.access(f)}catch{await fs.writeFile(f,i,"utf8")}}
async function read(f,d=[]){try{return JSON.parse(await fs.readFile(f,"utf8"))}catch{return d}}async function write(f,d){const t=f+".tmp";await fs.writeFile(t,JSON.stringify(d,null,2),"utf8");await fs.rename(t,f)}function json(res,s,d){res.writeHead(s,{"content-type":"application/json; charset=utf-8","cache-control":"no-store"});res.end(JSON.stringify(d))}function body(req){return new Promise((res,rej)=>{let x="";req.on("data",c=>{x+=c;if(x.length>MAX)rej(new Error("payload too large"))});req.on("end",()=>{try{res(x?JSON.parse(x):{})}catch{rej(new Error("invalid JSON"))}});req.on("error",rej)})}function key(){if(!MASTER||MASTER===DEV)throw Object.assign(new Error("Set a strong LEVELING_MASTER_KEY before storing API keys"),{status:500,code:"master_key_required"});return MASTER}function preset(id){return providerCatalog.find(x=>x.id===id)}function ctx(p){return Number(p.contextWindow||process.env.LEVELING_CONTEXT_TOKENS||32768)}
async function call(p,secret,payload){const f=fitPayload(payload.messages||[],ctx(p),Number(payload.maxTokens||1600)),model=payload.model||p.model;if(p.adapter==="anthropic"){const r=await fetch(p.baseUrl+"/messages",{method:"POST",headers:{"content-type":"application/json","x-api-key":secret,"anthropic-version":"2023-06-01"},body:JSON.stringify({model,max_tokens:f.maxOutputTokens,temperature:payload.temperature??.2,system:f.messages.filter(m=>m.role==="system").map(m=>String(m.content)).join("\n"),messages:f.messages.filter(m=>m.role!=="system").map(m=>({role:m.role==="assistant"?"assistant":"user",content:String(m.content)}))})});if(!r.ok)throw Object.assign(new Error(await r.text()),{status:r.status});const x=await r.json();return{content:(x.content||[]).map(a=>a.text||"").join(""),usage:x.usage||{}}}if(p.adapter==="gemini"){const r=await fetch(p.baseUrl+"/models/"+encodeURIComponent(model)+":generateContent?key="+encodeURIComponent(secret),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contents:f.messages.filter(m=>m.role!=="system").map(m=>({role:m.role==="assistant"?"model":"user",parts:[{text:String(m.content)}]})),systemInstruction:f.messages.some(m=>m.role==="system")?{parts:[{text:f.messages.filter(m=>m.role==="system").map(m=>String(m.content)).join("\n")}]}:undefined,generationConfig:{temperature:payload.temperature??.2,maxOutputTokens:f.maxOutputTokens}})});if(!r.ok)throw Object.assign(new Error(await r.text()),{status:r.status});const x=await r.json();return{content:x.candidates?.[0]?.content?.parts?.map(a=>a.text||"").join("")||"",usage:x.usageMetadata||{}}}const base=String(p.baseUrl||"").replace(/\/$/,"");if(!base)throw Object.assign(new Error("Provider base URL is empty"),{status:400});const r=await fetch(base+"/chat/completions",{method:"POST",headers:{"content-type":"application/json",authorization:"Bearer "+secret},body:JSON.stringify({model,messages:f.messages,temperature:payload.temperature??.2,max_tokens:f.maxOutputTokens})});if(!r.ok)throw Object.assign(new Error(await r.text()),{status:r.status});const x=await r.json();return{content:x.choices?.[0]?.message?.content||"",usage:x.usage||{},context:{inputTokens:f.inputTokens,contextWindow:f.contextWindow}}}
async function route(payload,trace=()=>{}){const list=await read(PROVIDERS);const lp=localProvider();if(lp)list.push(lp);if(!list.length)throw Object.assign(new Error("No local model or external provider is configured"),{status:503,code:"no_provider"});return new ProviderRouter({providers:list,decrypt:b=>decryptSecret(b,key()),callProvider:call,trace}).run(payload,payload.providerId||"auto")}
async function news(limit=8){const r=await fetch("https://news.google.com/rss/search?q=AI&hl=en-IN&gl=IN&ceid=IN:en",{headers:{"user-agent":"Leveling/0.13"}});if(!r.ok)throw Object.assign(new Error("AI news feed returned HTTP "+r.status),{status:r.status});const xml=await r.text();return[...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)].slice(0,limit).map(m=>{const b=m[1];return{title:b.match(/<title>([\s\S]*?)<\/title>/)?.[1]?.replace(/<!\[CDATA\[|\]\]>/g,"")||"",link:b.match(/<link>([\s\S]*?)<\/link>/)?.[1]||"",pubDate:b.match(/<pubDate>([\s\S]*?)<\/pubDate>/)?.[1]||""}}).filter(x=>x.title)}
async function report(prompt,providerId){const n=await news(),digest=n.map((x,i)=>(i+1)+". "+x.title+"\n"+x.link).join("\n");const r=await route({providerId,messages:[{role:"system",content:"Summarize ONLY supplied news items. Include source links. Never invent facts."},{role:"user",content:"Goal: "+prompt+"\n\n"+digest}],maxTokens:1100});return{content:r.content,news:n,provider:r.provider,usage:r.usage}}
async function email(x){const{default:nodemailer}=await import("nodemailer");if(!process.env.SMTP_HOST||!process.env.SMTP_USER||!process.env.SMTP_PASS)throw Object.assign(new Error("SMTP is not configured"),{status:501});const t=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE||"false")==="true",auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});return t.sendMail({from:process.env.MAIL_FROM||process.env.SMTP_USER,to:x.to,subject:x.subject,text:x.text,html:x.html})}
async function executeWorkflow(task,testOnly){const out=[];let content="";for(const n of task.nodes||[]){if(n.type==="trigger"){out.push({id:n.id,status:"ready"});continue}if(n.type==="research"){try{const ns=await news();out.push({id:n.id,status:"completed",count:ns.length})}catch(e){out.push({id:n.id,status:"failed",error:String(e.message||e)})}}else if(n.type==="verify")out.push({id:n.id,status:"completed"});else if(n.type==="llm"){try{const r=await report(task.prompt,task.providerId);content=r.content;out.push({id:n.id,status:"completed",provider:r.provider})}catch(e){out.push({id:n.id,status:"failed",error:String(e.message||e)})}}else if(n.type==="media.video")out.push({id:n.id,status:"blocked",error:"No real video-generation adapter configured",durationSeconds:20});else if(n.type==="deliver"){for(const c of n.connectors||[]){if(testOnly){out.push({id:n.id,connector:c,status:"dry-run"})}else if(c==="email"){try{await email({to:process.env.MAIL_TO||process.env.SMTP_USER,subject:task.name+" — Leveling",text:content,html:"<pre>"+String(content).replace(/[&<>]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[m]))+"</pre>"});out.push({id:n.id,connector:c,status:"completed"})}catch(e){out.push({id:n.id,connector:c,status:"failed",error:String(e.message||e)})}}else out.push({id:n.id,connector:c,status:"blocked",error:"Publisher adapter requires real OAuth implementation"})}}else out.push({id:n.id,status:"completed"})}return{ok:out.every(x=>x.status!=="failed"),nodeResults:out,content,testOnly}}
async function zip(){const name="leveling-workspace-"+Date.now()+".zip",out=path.join(ROOT,name);await new Promise((res,rej)=>{const s=fsSync.createWriteStream(out),a=archiver("zip",{zlib:{level:9}});s.on("close",res);a.on("error",rej);a.pipe(s);a.glob("**/*",{cwd:ROOT,ignore:[".leveling/**","node_modules/**","dist/**","*.zip","models/legacy/**"]});a.finalize()});return name}
const server=http.createServer(async(req,res)=>{try{await ensure();const u=new URL(req.url,"http://127.0.0.1");
if(req.method==="GET"&&u.pathname==="/api/health"){const local=await inspectLocalModel();return json(res,200,{ok:true,version:"0.13.0",workspace:ROOT,secureMaster:Boolean(MASTER&&MASTER!==DEV),effectiveContextTokens:local.contextWindow,localModel:local})}
if(req.method==="GET"&&u.pathname==="/api/models"){return json(res,200,{local:await inspectLocalModel(),legacy:{id:"legacy-14.4m",parameterCount:14400000,status:"isolated-recovery-only"}})}
if(req.method==="GET"&&u.pathname==="/api/providers"){return json(res,200,{catalog:providerCatalog,configured:(await read(PROVIDERS)).map(p=>{const x={...p};delete x.secret;return x})})}
if(req.method==="POST"&&u.pathname==="/api/providers"){const b=await body(req),p=preset(b.preset);if(!b.name||!b.model||!b.apiKey)return json(res,400,{error:"name, model and apiKey are required"});const baseUrl=String(b.baseUrl||p?.baseUrl||"").replace(/\/$/,"");if(!baseUrl)return json(res,400,{error:"Base URL is required"});const list=await read(PROVIDERS);const row={id:crypto.randomUUID(),name:String(b.name),model:String(b.model),baseUrl,adapter:String(b.adapter||p?.adapter||"openai-compatible"),priority:Number(b.priority||100),enabled:true,providerPreset:String(b.preset||"custom"),contextWindow:Number(b.contextWindow||32768),secret:encryptSecret(String(b.apiKey),key())};list.push(row);await write(PROVIDERS,list);const safe={...row};delete safe.secret;return json(res,201,safe)}
if(req.method==="POST"&&u.pathname==="/api/providers/test"){const b=await body(req),p=(await read(PROVIDERS)).find(x=>x.id===b.providerId);if(!p)return json(res,404,{error:"Provider not found"});try{const x=await call(p,decryptSecret(p.secret,key()),{messages:[{role:"user",content:"Reply exactly LEVELING_PROVIDER_OK"}],maxTokens:50});return json(res,200,{ok:true,response:x.content,provider:p.name})}catch(e){return json(res,Number(e.status||500),{ok:false,error:String(e.message||e),status:e.status||500})}}
if(req.method==="DELETE"&&u.pathname.startsWith("/api/providers/")){const id=decodeURIComponent(u.pathname.slice("/api/providers/".length)),list=await read(PROVIDERS);await write(PROVIDERS,list.filter(x=>x.id!==id));return json(res,200,{ok:true})}
if(req.method==="POST"&&u.pathname==="/api/chat"){const b=await body(req),trace=[];try{return json(res,200,{...await route({providerId:b.providerId,messages:b.messages||[],maxTokens:b.maxTokens||1600,temperature:b.temperature},x=>trace.push(x)),trace})}catch(e){return json(res,Number(e.status||503),{error:String(e.message||e),status:e.status||503,code:e.code,failures:e.failures||[],trace})}}
if(req.method==="GET"&&u.pathname==="/api/workspace/tree")return json(res,200,{root:ROOT,tree:await walkTree(ROOT)});
if(req.method==="GET"&&u.pathname==="/api/workspace/file"){const r=u.searchParams.get("path")||"";return json(res,200,{path:r,content:await fs.readFile(safePath(ROOT,r),"utf8")})}
if(req.method==="POST"&&u.pathname==="/api/workspace/file"){const b=await body(req),t=assertWorkspaceWritePath(ROOT,String(b.path||""));await fs.mkdir(path.dirname(t),{recursive:true});await fs.writeFile(t,String(b.content??""),"utf8");return json(res,200,{ok:true,path:b.path})}
if(req.method==="POST"&&u.pathname==="/api/workspace/run"){const b=await body(req),r=await runCommand(ROOT,String(b.command),Array.isArray(b.args)?b.args:[],Number(b.timeoutMs||30000));return json(res,200,{ok:r.code===0,...r})}
if(req.method==="POST"&&u.pathname==="/api/workspace/export")return json(res,200,{ok:true,name:await zip()});
if(req.method==="GET"&&u.pathname==="/api/workspace/export"){const name=u.searchParams.get("name")||"";if(!/^leveling-workspace-\d+\.zip$/.test(name))return json(res,400,{error:"invalid export name"});const d=await fs.readFile(safePath(ROOT,name));res.writeHead(200,{"content-type":"application/zip","content-disposition:"attachment; filename=\""+name+"\""});res.end(d);return}
if(req.method==="POST"&&u.pathname==="/api/agent/plan"){const b=await body(req);try{if(b.providerId){const r=await route({providerId:b.providerId,messages:[{role:"system",content:"Return ONLY JSON {summary,steps,files,commands}; paths must be workspace-relative; no destructive commands."},{role:"user",content:String(b.prompt||"")}],maxTokens:3200});return json(res,200,{ok:true,plan:parseModelPlan(r.content),provider:r.provider})}return json(res,200,{ok:true,plan:buildFallbackPlan(b.prompt),provider:"deterministic scaffold"})}catch(e){return json(res,Number(e.status||500),{error:String(e.message||e)})}}
if(req.method==="POST"&&u.pathname==="/api/agent/apply"){const b=await body(req);if(!b.plan)return json(res,400,{error:"plan required"});const results=[];for(const f of b.plan.files||[]){const t=assertWorkspaceWritePath(ROOT,String(f.path||""));await fs.mkdir(path.dirname(t),{recursive:true});await fs.writeFile(t,String(f.content||""),"utf8");results.push({path:f.path,action:f.action||"write"})}return json(res,200,{ok:true,results})}
if(req.method==="POST"&&u.pathname==="/api/agent/execute"){const b=await body(req);try{return json(res,200,await (async()=>{let last="";for(let a=1;a<=Math.min(3,Math.max(1,Number(b.maxAttempts||3)));a++){const planned=await agentPlanExec(String(b.prompt||""),b.providerId);await applyExec(planned.plan);const cmds=planned.plan.commands?.length?planned.plan.commands:[{command:"npm",args:["run","check"]}];let pass=true;for(const c of cmds){try{const r=await runCommand(ROOT,c.command,c.args,120000);if(r.code!==0){pass=false;last=r.stderr||r.stdout||"command failed";break}}catch(e){pass=false;last=String(e.message||e);break}}if(pass)return{ok:true,plan:planned.plan,trace:["attempt "+a+" passed"],lastError:""};if(b.providerId&&b.providerId!=="local"){try{const rr=await route({providerId:b.providerId,messages:[{role:"system",content:"Return ONLY JSON repair plan {summary,steps,files,commands}."},{role:"user",content:"Task:\n"+b.prompt+"\nFailure:\n"+last}],maxTokens:3200});planned.plan=parseModelPlan(rr.content)}catch{}}}return{ok:false,trace:["build failed"],lastError:last}})())}catch(e){return json(res,Number(e.status||500),{error:String(e.message||e)})}}
if(req.method==="POST"&&u.pathname==="/api/automation/compile"){const b=await body(req),w=compileWorkflow(b.prompt,b.name);validateWorkflow(w);return json(res,200,{ok:true,workflow:w})}
if(req.method==="GET"&&u.pathname==="/api/automations")return json(res,200,{tasks:await read(TASKS)});
if(req.method==="POST"&&u.pathname==="/api/automations"){const b=await body(req);validateWorkflow(b);const list=await read(TASKS);const row={...b,id:b.id||crypto.randomUUID(),enabled:Boolean(b.enabled),lastRun:null,lastResult:null,createdAt:new Date().toISOString()};list.push(row);await write(TASKS,list);return json(res,201,row)}
if(req.method==="POST"&&u.pathname==="/api/automations/test"){const b=await body(req);validateWorkflow(b.task||b);return json(res,200,await executeWorkflow(b.task||b,true))}
if(req.method==="POST"&&u.pathname.match(/^\/api\/automations\/[^/]+\/run$/)){const id=u.pathname.split("/")[3],list=await read(TASKS),task=list.find(x=>x.id===id);if(!task)return json(res,404,{error:"Automation not found"});const r=await executeWorkflow(task,false);task.lastRun=new Date().toISOString();task.lastResult=r;await write(TASKS,list);return json(res,200,r)}
if(req.method==="PUT"&&u.pathname.match(/^\/api\/automations\/[^/]+$/)){const id=u.pathname.split("/")[3],b=await body(req),list=await read(TASKS),i=list.findIndex(x=>x.id===id);if(i<0)return json(res,404,{error:"Automation not found"});const next={...list[i],...b};validateWorkflow(next);list[i]=next;await write(TASKS,list);return json(res,200,next)}
if(req.method==="DELETE"&&u.pathname.match(/^\/api\/automations\/[^/]+$/)){const id=u.pathname.split("/")[3],list=await read(TASKS);await write(TASKS,list.filter(x=>x.id!==id));return json(res,200,{ok:true})}
if(req.method==="GET"&&u.pathname==="/api/connectors")return json(res,200,{catalog:connectorCatalog});
if(req.method==="GET"&&u.pathname==="/api/learning/status")return json(res,200,{...(await read(LEARNING,{})),legacyCheckpoint:{parameterCount:14400000,policy:"isolated-recovery-only"}});
if(req.method==="POST"&&u.pathname==="/api/learning/collect"){const b=await body(req);try{const r=await collectUrl(String(b.url||""),Array.isArray(b.allowlist)?b.allowlist:[]);await saveStaged(ROOT,r);const s=await read(LEARNING,{});s.stagedRecords=Number(s.stagedRecords||0)+1;await write(LEARNING,s);return json(res,200,{ok:true,stage:"staged",record:r})}catch(e){return json(res,Number(e.status||400),{error:String(e.message||e)})}}
if(req.method==="POST"&&u.pathname==="/api/learning/prepare"){const s=await read(LEARNING,{}),d=path.join(ROOT,".leveling","datasets"),f=path.join(d,"staged.jsonl");let raw="";try{raw=await fs.readFile(f,"utf8")}catch{}const rows=raw.split("\n").filter(Boolean).map(x=>JSON.parse(x)),curated=curate(rows,.72);await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,"curated.jsonl"),curated.map(x=>JSON.stringify(x)).join("\n")+(curated.length?"\n":""),"utf8");s.curatedRecords=curated.length;await write(LEARNING,s);return json(res,200,{ok:true,curatedRecords:curated.length})}
if(req.method==="POST"&&u.pathname==="/api/media/storyboard"){const b=await body(req);let scenes=[];if(b.providerId){try{const r=await route({providerId:b.providerId,messages:[{role:"system",content:"Return ONLY JSON {scenes:[{title,shot,prompt,durationSeconds}]}, each <=20 seconds."},{role:"user",content:String(b.prompt||"")}],maxTokens:1800});const st=r.content||"",a=st.indexOf("{"),z=st.lastIndexOf("}");if(a>=0&&z>a)scenes=normalizeStoryboard(JSON.parse(st.slice(a,z+1)).scenes||[])}catch{}}if(!scenes.length)scenes=normalizeStoryboard([{title:"Opening",shot:"Establishing",prompt:String(b.prompt||""),durationSeconds:20},{title:"Development",shot:"Medium",prompt:String(b.prompt||""),durationSeconds:20},{title:"Transition",shot:"Moving",prompt:String(b.prompt||""),durationSeconds:20},{title:"Closing",shot:"Wide",prompt:String(b.prompt||""),durationSeconds:20}]);return json(res,200,{ok:true,scenes,generatedMedia:false,kind:"storyboard-plan"})}
if(req.method==="POST"&&u.pathname==="/api/media/image"){return json(res,501,{error:"Image generation adapter is not configured in this build; no fake image result will be returned",generatedMedia:false})}
if(req.method==="POST"&&u.pathname==="/api/media/video"){return json(res,501,{error:"Video generation adapter is not configured; clip contract enforces <=20s",request:validateClipRequest(await body(req)),generatedMedia:false})}
if(u.pathname==="/"){try{const d=await fs.readFile(path.resolve("./dist/index.html"));res.writeHead(200,{"content-type":"text/html"});res.end(d);return}catch{}}try{const t=safePath(path.resolve("./dist"),u.pathname.replace(/^\//,""));const d=await fs.readFile(t);res.writeHead(200,{"content-type":"text/plain"});res.end(d);return}catch{}return json(res,404,{error:"Not found"})
}catch(e){return json(res,Number(e.status||500),{error:String(e.message||e),status:e.status||500,code:e.code})}});
async function agentPlanExec(p,id){if(id){const r=await route({providerId:id,messages:[{role:"system",content:"Return ONLY JSON {summary,steps,files,commands}; no destructive commands."},{role:"user",content:p}],maxTokens:3200});return{plan:parseModelPlan(r.content),provider:r.provider}}return{plan:buildFallbackPlan(p),provider:"deterministic scaffold"}}async function applyExec(p){const results=[];for(const f of p.files||[]){const t=assertWorkspaceWritePath(ROOT,String(f.path||""));await fs.mkdir(path.dirname(t),{recursive:true});await fs.writeFile(t,String(f.content||""),"utf8");results.push(f.path)}return results}
server.listen(PORT,()=>console.log("Leveling v0.13 core http://127.0.0.1:"+PORT));setInterval(async()=>{const list=await read(TASKS);let changed=false;for(const t of list)if(isDueToday(t)){t.lastResult=await executeWorkflow(t,false);t.lastRun=new Date().toISOString();changed=true}if(changed)await write(TASKS,list)},30000);
