function extractJson(text){
  const raw=String(text||"").replace(/^\s*\`\`\`json/i,"").replace(/\`\`\`\s*$/i,"").trim();
  const start=raw.indexOf("{"),end=raw.lastIndexOf("}");
  if(start<0||end<=start) throw new Error("Model did not return a JSON plan");
  return JSON.parse(raw.slice(start,end+1));
}
export function normalizePlan(input){
  return {
    summary:String(input.summary||"Implement the requested task."),
    steps:(Array.isArray(input.steps)?input.steps:[]).slice(0,20).map((s,i)=>({id:String(s.id||i+1),title:String(s.title||"Step "+(i+1)),detail:String(s.detail||""),status:"pending"})),
    files:(Array.isArray(input.files)?input.files:[]).slice(0,100).map(f=>({path:String(f.path||""),action:f.action==="update"?"update":"create",content:String(f.content||"")})).filter(f=>f.path),
    commands:(Array.isArray(input.commands)?input.commands:[]).slice(0,30).map(c=>({command:String(c.command||""),args:Array.isArray(c.args)?c.args.map(String):[]})).filter(c=>c.command)
  };
}
export function buildFallbackPlan(prompt){
  const safeName=String(prompt||"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,40)||"new-project";
  return normalizePlan({
    summary:"Starter workspace scaffold for: "+prompt,
    steps:[{id:"1",title:"Create project skeleton",detail:"Create a minimal runnable workspace."},{id:"2",title:"Add entrypoint",detail:"Add a small app entrypoint and configuration."},{id:"3",title:"Verify",detail:"Run project verification."}],
    files:[{path:safeName+"/README.md",action:"create",content:"# "+safeName+"\n\nGenerated by leveling v0.12.\n\nTask: "+prompt+"\n"}],
    commands:[]
  });
}
export function parseModelPlan(text){return normalizePlan(extractJson(text));}
