export const providerCatalog = [
  ["openai","OpenAI","openai-compatible","https://api.openai.com/v1","gpt-4.1-mini"],
  ["anthropic","Anthropic","anthropic","https://api.anthropic.com/v1","claude-sonnet-4-5"],
  ["gemini","Google Gemini","gemini","https://generativelanguage.googleapis.com/v1beta","gemini-2.5-flash"],
  ["groq","Groq","openai-compatible","https://api.groq.com/openai/v1","llama-3.3-70b-versatile"],
  ["mistral","Mistral","openai-compatible","https://api.mistral.ai/v1","mistral-small-latest"],
  ["deepseek","DeepSeek","openai-compatible","https://api.deepseek.com/v1","deepseek-chat"],
  ["openrouter","OpenRouter","openai-compatible","https://openrouter.ai/api/v1","openai/gpt-4.1-mini"],
  ["together","Together AI","openai-compatible","https://api.together.xyz/v1","meta-llama/Llama-3.3-70B-Instruct-Turbo"],
  ["fireworks","Fireworks AI","openai-compatible","https://api.fireworks.ai/inference/v1","accounts/fireworks/models/llama-v3p1-70b-instruct"],
  ["cerebras","Cerebras","openai-compatible","https://api.cerebras.ai/v1","llama-3.3-70b"],
  ["perplexity","Perplexity","openai-compatible","https://api.perplexity.ai","sonar"],
  ["xai","xAI","openai-compatible","https://api.x.ai/v1","grok-4"],
  ["cohere","Cohere","openai-compatible","https://api.cohere.com/compatibility/v1","command-a"],
  ["ai21","AI21 Labs","openai-compatible","https://api.ai21.com/studio/v1","jamba-mini-1.6"],
  ["sambanova","SambaNova","openai-compatible","https://api.sambanova.ai/v1","Meta-Llama-3.3-70B-Instruct"],
  ["huggingface","Hugging Face","openai-compatible","https://router.huggingface.co/v1","meta-llama/Llama-3.3-70B-Instruct"],
  ["nvidia","NVIDIA NIM","openai-compatible","https://integrate.api.nvidia.com/v1","meta/llama-3.3-70b-instruct"],
  ["deepinfra","DeepInfra","openai-compatible","https://api.deepinfra.com/v1/openai","meta-llama/Llama-3.3-70B-Instruct"],
  ["replicate","Replicate","replicate","https://api.replicate.com/v1","meta/meta-llama-3-70b-instruct"],
  ["azure-openai","Azure OpenAI","openai-compatible","","gpt-4.1"],
  ["github-models","GitHub Models","openai-compatible","https://models.inference.ai.azure.com","gpt-4o-mini"],
  ["siliconflow","SiliconFlow","openai-compatible","https://api.siliconflow.cn/v1","Qwen/Qwen3-32B"],
  ["novita","Novita AI","openai-compatible","https://api.novita.ai/v3/openai","meta-llama/llama-3.3-70b-instruct"],
  ["moonshot","Moonshot AI","openai-compatible","https://api.moonshot.ai/v1","kimi-k2"],
  ["zhipu","Zhipu AI","openai-compatible","https://open.bigmodel.cn/api/paas/v4","glm-4.5"],
  ["minimax","MiniMax","openai-compatible","https://api.minimax.io/v1","MiniMax-M2"],
  ["baichuan","Baichuan","openai-compatible","https://api.baichuan-ai.com/v1","Baichuan4"],
  ["yi","01.AI Yi","openai-compatible","https://api.lingyiwanwu.com/v1","yi-large"],
  ["volcengine","Volcengine Ark","openai-compatible","https://ark.cn-beijing.volces.com/api/v3","doubao-seed-1-6"],
  ["qwen","Alibaba Qwen","openai-compatible","https://dashscope-intl.aliyuncs.com/compatible-mode/v1","qwen-plus"],
  ["aleph-alpha","Aleph Alpha","custom","https://api.aleph-alpha.com","luminous-supreme-control"]
].map(([id,name,adapter,baseUrl,defaultModel]) => ({id,name,adapter,baseUrl,defaultModel}));
